services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: epam-user
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: task1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/ # Añadimos el directorio de inicialización de scripts
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network: