file.path.events=data/events.xml
file.path.tickets=data/tickets.xml
file.path.users=data/users.xml

spring.h2.console.enabled=true

spring.main.allow-bean-definition-overriding=true

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=artemis
spring.activemq.password=artemis

jms.message.destination=bookingQueue

flyway.user=epam-user
flyway.password=pwd123
flyway.schemas=tickets_database
flyway.url=jdbc:postgresql://localhost:5432/tickets_database
flyway.locations=classpath:evolutions


management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always

management.endpoints.web.exposure.include=health,flyway,info,metrics

spring.security.oauth2.client.registration.github.client-id=Ov23liOXZDvgmweaglRH
spring.security.oauth2.client.registration.github.client-secret=822a6bf675a12da145fd4f1443159a26537bea6b

spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/auth/callback
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.provider.github.user-name-attribute=id
